### PR TITLE
Fix rfc7519 labels on http-api-jwt-authorizer.md

### PR DESCRIPTION
**Pull request by rrrix**
Fixed backwards RFC7519 Sections 4.1.4/4.1.5 exp/nbt 'Before' (Expiration) and 'After' (Not Before) descriptions

*Description of changes:*

The `http-api-jwt-authorizer.md` documentation describes the "exp" (Expiration) and "nbt" (Not-Before) claims "inverse" of the correct usage.

It currently states:

> exp – Must be **after** the current time in UTC.
> nbf – Must be **before** the current time in UTC.

However: 
* `exp` means "Expiration". That means the time must be _before_ the current time in UTC 
* `nbf` means "Not Before". That means the time must be _after_ the current time in UTC.

Here's sections [4.1.4](https://tools.ietf.org/html/rfc7519#section-4.1.4) and [4.1.5](https://tools.ietf.org/html/rfc7519#section-4.1.5) from RFC7519:

```text
4.1.4.  "exp" (Expiration Time) Claim

   The "exp" (expiration time) claim identifies the expiration time on
   or after which the JWT MUST NOT be accepted for processing.  The
   processing of the "exp" claim requires that the current date/time
   MUST be before the expiration date/time listed in the "exp" claim.

4.1.5.  "nbf" (Not Before) Claim

   The "nbf" (not before) claim identifies the time before which the JWT
   MUST NOT be accepted for processing.  The processing of the "nbf"
   claim requires that the current date/time MUST be after or equal to
   the not-before date/time listed in the "nbf" claim.  Implementers MAY
   provide for some small leeway, usually no more than a few minutes, to
   account for clock skew.  Its value MUST be a number containing a
   NumericDate value.  Use of this claim is OPTIONAL.
```

Cheers!

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mcdwil** [comment]
Hi,

Thanks for reaching out. It looks like the RFC is written from the perspective of the current date/time relative to the token. The API Gateway docs are written from the perspective of token claims relative to the current time.

>- `exp` – Must be after the current time in UTC. 

For example, if the token expires at 22:00 today, it would be valid at 21:00 today. The `exp` token claim must be after the current time for API Gateway to authorize a request.

>- `nbf` – Must be before the current time in UTC. 

For example, if the token has an `nbf` claim of 10:00 today, it would be valid at 11:00 today. The `nbf` in the token must be before the current time for API Gateway to authorize a request.

Does that help clear things up?

Thanks,
Will

**Comment by rrrix** [comment]
Definitely, once you explain it that way! Perhaps it could be clarified in the documentation like this?

- exp – Value of token `exp` claim must be after the current time in UTC.
- nbf – Value of token `nbf` claim must be before the current time in UTC.

**Comment by mcdwil** [comment]
Great!  Sounds good - would you be willing to update your PR, or submit a new one with that change?

**Comment by mcdwil** [comment]
Closing due to inactivity. Feel free to open a new PR!

**Pull request closed without merging**
